### ISSUE TITLE
Textual representation of weekdays in Hungarian locale are off by 1 day

### ISSUE THREAD

**Issue by larsvandersangen** [fightbulc/moment.php#109]
When I format a date in Hungarian, the textual representation of the weekday is wrong. For Thursday 13th of July 2017, the Hungarian format echo's szerda (Wedsnesday).

I think the problem lies in the Hungarian (hu_HU) locale config. It says the week starts at [monday](https://github.com/fightbulc/moment.php/blob/master/src/Locales/hu_HU.php#L66), but the '[weekdays](https://github.com/fightbulc/moment.php/blob/master/src/Locales/hu_HU.php#L10)' config starts at 'vasárnap' (sunday).

Could be anything else, but it seems like that is the problem.

**Comment by fightbulc** [comment]
has been fixed by the last PR. Can you confirm?

**Comment by larsvandersangen** [comment]
+1 is fixed
