### ISSUE TITLE
Validating Apple InApp Receipts

### ISSUE THREAD

**Issue by Hirbod** [fightbulc/moment.php#118]
Hi,

I am currently validating Apple InApp Payment receipts, but it looks like none of the provided dates are useable with this lib.

```

    [purchase_date] => 2017-10-02 20:31:23 Etc/GMT
  | [purchase_date_ms] => 1506976283000
  | [purchase_date_pst] => 2017-10-02 13:31:23 America/Los_Angeles
  | [original_purchase_date] => 2017-10-02 16:02:08 Etc/GMT
  | [original_purchase_date_ms] => 1506960128000
  | [original_purchase_date_pst] => 2017-10-02 09:02:08 America/Los_Angeles
  | [expires_date] => 2017-10-02 20:36:23 Etc/GMT
  | [expires_date_ms] => 1506976583000
  | [expires_date_pst] => 2017-10-02 13:36:23 America/Los_Angeles
  | [web_order_line_item_id] => 1000000036446298
  | [is_trial_period] => false
```

Most importan is pruchase_date and expires date but I am still unsure how to validate things.
I could remove "Etc/GMT" from string (which is prob. the reason for moment.php to fail) but the time isn't correct then (its 22:50 now, so there is 2 hours difference)

Im not sure if this is going to be a rock-solid idea (remove Etc/GMT and add 2 hours)

**Comment by Hirbod** [comment]
Well I am an Idiot... using a simple strtotime() just fixed my problems...

**Comment by fightbulc** [comment]
Glad you found the solution :)
