### ISSUE TITLE
Unable to override custom tokens when already present

### ISSUE THREAD

**Issue by EvilLooney** [fightbulc/moment.php#132]
Hi,

After updating this library to a newer version, I noticed that the code I use does not work anymore. I am talking about this bit of code:
https://github.com/fightbulc/moment.php/issues/6#issuecomment-39033459

.. where I am redefining the `LLL` format.

It seems that this commit overrides my custom format with the ones included in the package:
https://github.com/fightbulc/moment.php/commit/627e3048aad3ae3b178e3e1570193b440e6655dd#diff-72cb2741b8b90242338647ce25c0b40f

Is there a workaround to this?

Thanks.

**Comment by fightbulc** [comment]
Duplicate #192
