### ISSUE TITLE
moment constructor with number don't always recognise unix time

### ISSUE THREAD

**Issue by nokiiam** [fightbulc/moment.php#161]
Hi,

the constructor of moment don't work with all unix time when they are passed without '@' in front of them

example : 
`new Moment(0)`
will create an exception
DateTime::__construct(): Failed to parse time string (0) at position 0 (0): Unexpected character

this is caused by the test to detect unix time in the resetDateTime being : 
`if (strlen((int)$dateTime) === 10)`
which don't detect unix time before 9 September 2001 01:46:40 (1000000000 in unix time)

**Comment by fightbulc** [comment]
will come in upcoming release
