### ISSUE TITLE
getRelative time is broken in many cases

### ISSUE THREAD

**Issue by blacknell** [fightbulc/moment.php#163]
1. Most of the locales are missing the `'ss'` relativeTime definition and the `if/then/else` logic misses many edge cases. In fact this logic doesn't closely follow the [Time from now definitions](https://momentjs.com/docs/#/displaying/fromnow/) in moment.js. In addition low numbers of seconds were reported as negative eg. 'in -7 seconds'

I've now fixed these in my fork and added to the unit tests. @fightbulc - if you don't agree with this logic please comment

2. However, this broken logic has also uncovered some failed units tests for Latvian and Russian localisations. I don't speak these languages but I could have a go with Google Translate. But I think my pull request would need some expert review perhaps by @LinMAD and @dypa who made most recent contributions to those locales. @fightbulc - please advise.

I'm ready to submit a pull request for above

**Comment by SeinopSys** [comment]
I just updated and I'm getting `Moment\MomentException : Locale string does not exist for key: relativeTime > ss` with the `en_US` locale.

**Comment by blacknell** [comment]
I got the same with `en_GB` although it seems `en_US` includes this and then overrides a couple of items.

That aside, I've fixed it and am waiting to submit a PR.

If you want a local temporary fix you could change your local copy of `en_GB.php` as follows

```
    "relativeTime"  => array(
        "future" => 'in %s',
        "past"   => '%s ago',
        "s"      => 'a few seconds',
        "ss"      => '%d seconds',
        "m"      => 'a minute',
```

**Comment by blacknell** [comment]
@SeinopSys - you should be ok now on `en_US`. fixed in `^1.28`

**Comment by SeinopSys** [comment]
@blacknell Indeed the issue seems resolved, thank you for the heads up!

**Comment by dypa** [comment]
@blacknell @fightbulc https://github.com/fightbulc/moment.php/blob/master/tests/unit/Moment/MomentRussianLocaleTest.php#L103 everything is good
