### ISSUE TITLE
Seemingly valid RFC2822 returned as invalid

### ISSUE THREAD

**Issue by ndom91** [fightbulc/moment.php#165]
Hi All, 

Im trying to parse an RFC2822 formatted DateTime and first change the timezone and then spit it back out as `Y-m-d H:i`

So far I have: 

```
$m = new \Moment\Moment($date);
$date2 =  $m->setTimezone('CET')->format('Y-m-d H:i');
```

And this works great for some cases, for example:

`Tue, 11 Dec 2018 14:12:01 +0000` gets transformed into `2018-12-11 15:12`

However on my next instance I am receiving the error message: `"Given date of "Tue, 11 Dec 2018 07:46:41 -0500" is invalid"`

If we look at the given datetime formatting: `Tue, 11 Dec 2018 07:46:41 -0500` This seems to be entirely valid RFC2822 formatting <sup>[1]</sup>

Any idea why this moment.php won't accept this?

**EDIT**: The normal PHP DateTime object works perfectly fine on these. For example, the following works 100%:

```
$date2 = DateTime::createFromFormat("D, d M Y H:i:s O", $date);
$date2 = new DateTime($date);
$date2 = $date2->format('Y-m-d  H:i:s O');
```
Here I am just missing the timezone change, otherwise I would just keep this tbh.

**EDIT2**: Fuck it, just did it with PHPs standard DateTime :)

```
$CET = new DateTimeZone('Europe/Berlin');
$date2 = DateTime::createFromFormat("D, d M Y H:i:s O", $date);
$timezone = $date2->getTimezone();
$date2 = new DateTime($date, $timezone);
$date2->setTimezone($CET);
$date2 = $date2->format('Y-m-d  H:i:s');
```

[1]: https://tools.ietf.org/html/rfc2822#section-1

**Comment by fightbulc** [comment]
release 1.28.1 will fix this
