### ISSUE TITLE
subtractMonths not working at the last day of the month

### ISSUE THREAD

**Issue by pushpak** [fightbulc/moment.php#20]
If i give a timestamp of 30th October everything works fine, but if i provide 31st October time then the subtractMonth fails and i get the current month time.

```php
$moment = new \Moment\Moment();
$moment->setTimestamp(1414750126); // optional 
$moment->subtractMonths(1);
$moment->startOf('month')->format(); //2014-10-01T00:00:00+0000 
$moment->endOf('month')->format(); //2014-10-31T23:59:59+0000
```

Anything between the unixtime `1412121600` and `1414799999` causes this error

php version `5.4.26`

**Comment by fightbulc** [comment]
Hey man. I had a look and thought this would be a quick solution. However, this is actual not a bug. It happens for all months with unequal days. In your particular case the September does not have the 31st day. Therefore, PHP jumps into the next month.

I made a quick fix but noticed that this would be the same case for ```addMonths``` and actually also for ```add/sub years```. Additionally, you it also has to work for adding/subtracting multiple months.

You see, its not just a simple one.
