### ISSUE TITLE
Calendar() feature request

### ISSUE THREAD

**Issue by Hirbod** [fightbulc/moment.php#29]
Hi @fightbulc,

I'm building something similar like the facebook timeline. It would be nice if you could add an optional feature for the calendar. I would like to have the ability to set an optional feature for "today". Instead of showing "today at xxx" I'd like to have "1 hour ago, 2 hours ago" till 8 hours ago, after this, when not > 0 o'clock, showing today at XXX.

I think this would be a very helpful and nice feature request. What you think?

**Comment by Senorsen** [comment]
+1

**Comment by fightbulc** [comment]
Hey to the both of you. You know that there is a ```relativeTime``` feature?

```php
$m = new Moment('2015-05-03T10:00:00', 'Europe/Berlin');
echo $m->fromNow()->getRelative(); // 4 hours ago
```

**Comment by Hirbod** [comment]
PERFECT! THANKS!
