### ISSUE TITLE
Doesn't work on PHP 5.3.* - requires PHP >= 5.4

### ISSUE THREAD

**Issue by ruicampos** [fightbulc/moment.php#32]
I have tested latest version (1.6.3) on PHP 5.3.29:
````
PHP 5.3.29 (cli) (built: Aug 14 2014 14:15:02)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies
```

And it gives parse errors:

```
PHP Parse error:  syntax error, unexpected '[', expecting ')' in /var/www/smarkio.dev/lib/vendor/fightbulc/moment/src/Moment.php on line 657
````

This is because [ ] notation of arrays is being used which was introduced only on PHP 5.4 - [http://php.net/manual/en/language.types.array.php](http://php.net/manual/en/language.types.array.php)
> 
> (...)
> 
> **As of PHP 5.4 you can also use the short array syntax, which replaces array() with []**.

**Comment by fightbulc** [comment]
Hey @ruicampos. Just pushed a fix release. Thanks!
