### ISSUE TITLE
Ordinal quickfix doesn't handle all cases (noted for en_US, en_GB)

### ISSUE THREAD

**Issue by jabjab** [fightbulc/moment.php#37]
Is the quickfix described in https://github.com/fightbulc/moment.php#iv-fixed-ordinal-representations only for 'WS', or is it supposed to work for other formatting as well?

```php
$result = (new Moment('2015-03-31T20:00:00+0000'))->format('l, dS F Y');
```

Expected result: `Tuesday, 31st March 2015`
Actual result: `Tuesday, 31rd March 2015`

I believe it's recommended to not use ordinals in dates like "March 31, 2015" for en_US, but this still seems like an annoying bug.

**Comment by fightbulc** [comment]
Hey there. Thanks for spotting this. Just pushed a fix and released a new version.

https://github.com/fightbulc/moment.php/commit/9d580ef64bfa8d5eae389a5f439171918c0ff724

Cheers from Berlin
