### ISSUE TITLE
Hi there, here it is the it_IT

### ISSUE THREAD

**Issue by macfighterpilot** [fightbulc/moment.php#38]
Hi,
i just want to help you build this repo and since i didn't know how to be a contributor or to make a pull request, here it is the it_IT file:

<?php

// moment.js locale configuration
// locale => italia italiano (it_IT)
// author => Marco Micheli => https=>//github.com/macfighterpilot

return array(
    "months"        => explode('_', 'Gennaio_Febbraio_Marzo_Aprile_Maggio_Giugno_Luglio_Agosto_Settembre_Ottobre_Novembre_Dicembre'),
    "monthsShort"   => explode('_', 'Gen_Feb_Mar_Apr_Mag_Giu_Lug_Ago_Set_Ott_Nov_Dic'),
    "weekdays"      => explode('_', 'Lunedì_Martedì_Mercoledì_Giovedì_Venerdì_Sabato_Domenica'),
    "weekdaysShort" => explode('_', 'Lun_Mar_Mer_Gio_Ven_Sab_Dom'),
    "calendar"      => array(
        "sameDay"  => '[Oggi]',
        "nextDay"  => '[Domani]',
        "lastDay"  => '[Ieri]',
        "lastWeek" => '[Scorsa] l',
        "sameElse" => 'l',
        "withTime" => '[alle] H:i',
        "default"  => 'd/m/Y',
    ),
    "relativeTime"  => array(
        "future" => 'tra %s',
        "past"   => '%s fa',
        "s"      => 'pochi secondi',
        "m"      => 'un minuto',
        "mm"     => '%d minuti',
        "h"      => 'una ora',
        "hh"     => '%d ore',
        "d"      => 'un giorno',
        "dd"     => '%d giorni',
        "M"      => 'un mese',
        "MM"     => '%d mesi',
        "y"      => 'un anno',
        "yy"     => '%d anni',
    ),
    "ordinal"       => function ($number)
    {
        return $number . '';
    },
    "week"          => array(
        "dow" => 1, // Monday is the first day of the week.
        "doy" => 4  // The week that contains Jan 4th is the first week of the year.
    ),
);

**Comment by fightbulc** [comment]
Hey Marco. Thanks for your time! Just added it to the library.

Greetings from Berlin
