### ISSUE TITLE
ISO8601 includes the mysql datetime formate as well?

### ISSUE THREAD

**Issue by ptica** [fightbulc/moment.php#44]
Hi,
from the README it looks like moment.php parses only the datetimes with the T time separator,
and as there is no option how to parse custom formatted strings(?) I've originally thought that I could not use this nice library.

But it turns out that the mysql 'Y-m-d H:i:s' is perfectly ok for the constructor after all, maybe a example in the README could assure others to try this library as well!

**Comment by fightbulc** [comment]
Hey there. Good point. Will add all valid formats to the README. Thanks for pointing this out

**Comment by lenamtl** [comment]
+1

**Comment by fightbulc** [comment]
added some more information: https://github.com/fightbulc/moment.php#accepted-date-formats
