### ISSUE TITLE
startOf and endOf don't seem to set the value for week, quarter, and month

### ISSUE THREAD

**Issue by akoebbe** [fightbulc/moment.php#46]
I was trying to do `$date1->startOf('week');` and I was expecting $date1 to change to the first day of the week, but it didn't. After looking at the code I see that minute, hour, day, and year all use setTime or setDate changing the state of the object, but week, quarter, and month only return a new Moment and don't adjust the current instance. This is the same for endOf. Is this by design?

**Comment by fightbulc** [comment]
thanks for spotting this. cheers from Berlin
