### ISSUE TITLE
Wrong name of the month

### ISSUE THREAD

**Issue by Hirbod** [fightbulc/moment.php#50]
Hi @fightbulc,

I have following string:
 
```php
$message['createdate'] = "2015-06-14 20:46:22"; // from MySQL
$messages[$key]['date'] = (new \Moment\Moment($message['createdate'], 'Europe/Berlin'))->format('d. F');

// Should return 14. Juni
```

Should return "14. Juni", but it return "14. Juli".

I'll update to the newest version now, but I guess the bug is somewhere else.

**Comment by Hirbod** [comment]
The newest version did not change something

**Comment by Hirbod** [comment]
For now, this is my quick and dirty workaround

```php
$messages[$key]['date'] = (new \Moment\Moment($message['createdate'], 'Europe/Berlin'))->subtractMonths(1)->format('d. F');
```

just added subtractMonths(1) to hack around.

**Comment by Hirbod** [comment]
ping @fightbulc

**Comment by fightbulc** [comment]
Hey there. I went biking through Europe for the last two month. I am back now and will have a look again. Sorry for the delay.

Cheers :)

**Comment by Hirbod** [comment]
Now I'm jealous

**Comment by fightbulc** [comment]
Hey. So I pulled all requests and had a look at your issue but all runs normal. I wrote some tests to see what comes back. You can test it yourself: pull the current master and run ```vendor/bin/phpunit -c tests/build.xml```. There is a test file called ```MomentGermanLocaleTest.php``` which runs your case.

```php
$string = '2015-06-14 20:46:22';
$moment = new Moment($string, 'Europe/Berlin');
$this->assertEquals('14. Juni', $moment->format('d. F'));
```

**Comment by Hirbod** [comment]
@fightbulc 
Eben wieder gestestet. Es kommt "18. September" dabei raus. Getestet auf zwei unterschiedlichen Servern.

```php
$date = "2015-08-18 19:32:27";
$messages[$key]['date'] = (new \Moment\Moment($date, 'Europe/Berlin'))->format('d. F');
// 18. September
```

**Comment by Hirbod** [comment]
https://gist.github.com/stursby/10ca27c81353625df4ea

Same error here. I'm using german language...

**Comment by fightbulc** [comment]
Alright, just added moment.php to Travis: https://travis-ci.org/fightbulc/moment.php

All tests passed. This includes also the following tests:

```php
$string = '2015-06-14 20:46:22';
$moment = new Moment($string, 'Europe/Berlin');
$this->assertEquals('14. Juni', $moment->format('d. F'));

$string = '2015-03-08T15:14:53-0500';
$moment = new Moment($string, 'Europe/Berlin');
$this->assertEquals('08. März', $moment->format('d. F'));
```

Are there any files cached on your end, for instance the locale file?
I also ran your gist example from above and all works as expected.
Not quite sure what else I could do to receive your faulty results.

**Comment by Hirbod** [comment]
I don't know why it passes when you try.

```php
(new \Moment\Moment($message['createdate'], 'Europe/Berlin'))->format('d.m.Y');
// works (return 19.08.2015)
(new \Moment\Moment($message['createdate'], 'Europe/Berlin'))->format('d. F');
// fails (return 19. September)
```

Really can't figure out whats wrong here (as said, I tried on two debian dists. 5.4.41-0+deb7u1

**Comment by Hirbod** [comment]
When I change

```php
    "months"        => explode('_', 'Januar_Februar_März_April_Mai_Juni_Juli_August_September_Oktober_November_Dezember'),

//to

    "months"        => explode('_', 'Dezember_Januar_Februar_März_April_Mai_Juni_Juli_August_September_Oktober_November'),

// it works
```
