### ISSUE TITLE
Add support for ru_RU

### ISSUE THREAD

**Issue by fabienwarniez** [fightbulc/moment.php#68]
I want to use this bundle for my project, but I need support for Russian.

I am currently investigating adding support for that locale.

Is anyone else interested in helping?

**Comment by fightbulc** [comment]
Hey Fabien,

thanks for taking the initiative. It should be possible to use momentjs's locale file:
https://github.com/moment/moment/blob/develop/locale/ru.js

Time wise is tough for me at the moment. Maybe I find an hour over the weekend but not so sure about it.

Maybe somebody else got an hour?

**Comment by fightbulc** [comment]
also, there was already once the try:
https://github.com/fightbulc/moment.php/pull/56

**Comment by fabienwarniez** [comment]
Hi Tino,

It is unfortunately not as simple as creating another locale file, as Russian is more complex than most locales. The core code will have to be updated to support accusative / nominative.

As mentioned, someone else started adding support for Russian, maybe you could create a Russian branch and accept partial PRs so that we can collaboratively add support?

**Comment by fightbulc** [comment]
Hey Fabien. @wormen added the Russian locale. Not quite sure if all works out but its a start. Any possibility for you to have a look?

https://github.com/fightbulc/moment.php/pull/70

**Comment by kosha-industry** [comment]
in Russian language for plural forms use 3 different endings
Examples:
days - 1 день, 4 дня, 5 дней
hours - 1 час, 4 часа, 5 часов

<pre>
/**
 * returns ending for plural form of word by number and array of variants (1, 4, 5)
 * example variants for apples ['яблоко', 'яблока', 'яблок']
 */
function getNumEnding($number, $endingArray) {
  $number = $number % 100;
  if ($number >= 11 && $number <= 19) {
    $ending = $endingArray[2];
  } else {
    $i = $number % 10;
    switch ($i) {
      case (1):
        $ending = $endingArray[0];
        break;
      case (2):
      case (3):
      case (4):
        $ending = $endingArray[1];
        break;
      default:
        $ending = $endingArray[2];
    }
  }
  return $ending;
}
</pre>

and for ru_RU.php

<pre>
"relativeTime" => array(

  //...

  "dd" => function ($number) {
    // return "%d дней"; - not correct
    return getNumEnding($number, array("%d день", "%d дня", "%d дней"));
  },

  //...

),
</pre>

**Comment by fightbulc** [comment]
Thanks @kosha-industry. Implemented the fix in the last release: https://github.com/fightbulc/moment.php/commit/28c37656aabdb1bcfae3e7160af100f7b27b01e1

**Comment by kosha-industry** [comment]
Nice job, but add for others:
<pre>
mm: ['%d минуту', '%d минуты', '%d минут']
hh: ['%d час', '%d часа', '%d часов']
MM: ['%d месяц', '%d месяца', '%d месяцев']
yy: ['%d год', '%d года', '%d лет']
</pre>

**Comment by fightbulc** [comment]
up and live

**Comment by astax-t** [comment]
Ordinal suffixes are still not exactly correct. For the format "jS F Y", which produces "5th December 2016" in English, Russian gives "5ый декабря 2016". "5ый" uses masculine suffix "ый", while months names in Russian have neuter grammatical gender and all numbers should use the same suffux "е" - such as "1е декабря", "5е декабря", "12е июля".

**Comment by fightbulc** [comment]
@astax-t would be great if you could improve it

**Comment by dypa** [comment]
>would be great if you could improve it

@fabienwarniez fixed in #112
