### ISSUE TITLE
Try to discover default timezone from system settings

### ISSUE THREAD

**Issue by xorock** [fightbulc/moment.php#82]
I think it is better to set default timezone from date_default_timezone_get() or \DateTime->getTimezone()->getName() instead of forcing UTC.
Current behavior may lead to incorrect dates if someone forget to change this.

**Comment by fightbulc** [comment]
Hey there. UTC is standard so I will stick with this. However, I just pushed a version where you can set your default timezone to whatever you would like to.

See here how to:
https://github.com/fightbulc/moment.php#switch-timezones
