### ISSUE TITLE
How can i change the timezone?

### ISSUE THREAD

**Issue by Phisherman** [fightbulc/moment.php#85]
I need an other timezone than UTC. Is it possible to change the default timezone? It's very error-prone if I should need to change the timezone for every moment manually.

**Comment by fightbulc** [comment]
Hey there. I assume your datetime strings dont hold a timezone value. You could have wrapped the class to solve that issue. However, it might help also others. The new version 1.22 is up.

Here is how you adjust the default timezone:
https://github.com/fightbulc/moment.php#switch-timezones

**Comment by Phisherman** [comment]
@fightbulc Thanks. I've already implemented a wrapper. But the possibility of setting a default timezone is better.
