### ISSUE TITLE
error with php 7.1

### ISSUE THREAD

**Issue by zizohassan** [fightbulc/moment.php#95]
ErrorException in Moment.php line 0:
Declaration of Moment\Moment::setTime($hour, $minute, $second = NULL) should be compatible with DateTime::setTime($hour, $minute, $second = NULL, $microseconds = NULL)

**Comment by fightbulc** [comment]
Update your version. 1.25.1 fixed this already.

https://github.com/fightbulc/moment.php#changelog

**Comment by ConnerAiken** [comment]
I'm seeing this with version 1.28.x as well.

```
Warning: Declaration of Moment\Moment::createFromFormat($format, $time, ?DateTimeZone $timezone = NULL, ?Moment\FormatsInterface $formatsInterface = NULL) should be compatible with DateTime::createFromFormat($format, $time, $object = NULL) in /app/vendor/fightbulc/moment/src/Moment.php on line 1428
````
